### ISSUE TITLE
No native build was found for runtime=node abi=57 platform=linux arch=ia32

### ISSUE THREAD

**Issue by Konstantinusz** [maxogden/mount-url#2]
When I try to mount an URL I get some error messages:

```
/usr/lib/node_modules/mount-url/node_modules/node-gyp-build/index.js:28
  throw new Error('No native build was found for runtime=' + runtime + ' abi=' + abi + ' platform=' + platform + ' arch=' + arch)
  ^

Error: No native build was found for runtime=node abi=57 platform=linux arch=ia32
    at Function.load.path (/usr/lib/node_modules/mount-url/node_modules/node-gyp-build/index.js:28:9)
    at load (/usr/lib/node_modules/mount-url/node_modules/node-gyp-build/index.js:13:23)
    at Object.<anonymous> (/usr/lib/node_modules/mount-url/node_modules/fuse-bindings/index.js:1:99)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)

```

**Comment by Khalzy** [comment]
Did you find the solution for this?
